

const ARRANGEMENT = {
  T2B: "",
  L2R: "",
  R2L: "",
  CENTER: "",
};

/* 
  {
    code: "", // 键入事件的code $event.code
    value: "", // 键入值、$event.key

    isPress:false,// 是否被按压

    defaultValue: "",

    shiftValue: "",
    arrangement: ARRANGEMENT.CENTER,
    icon: "",
  }, 
*/

const ALL_KEYS = [
  {
    code: "Escape",
    value: "Escape",
    shiftValue: "",
    index: 0,
    isPress: false,
  },
  {
    code: "F1",
    value: "F1",
    shiftValue: "",
    index: 1,
    isPress: false,
  },
  {
    code: "F2",
    value: "F2",
    shiftValue: "",
    index: 2,
    isPress: false,
  },
  {
    code: "F3",
    value: "F3",
    shiftValue: "",
    index: 3,
    isPress: false,
  },
  {
    code: "F4",
    value: "F4",
    shiftValue: "",
    index: 4,
    isPress: false,
  },
  {
    code: "F5",
    value: "F5",
    shiftValue: "",
    index: 5,
    isPress: false,
  },
  {
    code: "F6",
    value: "F6",
    shiftValue: "",
    index: 6,
    isPress: false,
  },
  {
    code: "F7",
    value: "F7",
    shiftValue: "",
    index: 7,
    isPress: false,
  },
  {
    code: "F8",
    value: "F8",
    shiftValue: "",
    index: 8,
    isPress: false,
  },
  {
    code: "F9",
    value: "F9",
    shiftValue: "",
    index: 9,
    isPress: false,
  },
  {
    code: "F10",
    value: "F10",
    shiftValue: "",
    index: 10,
    isPress: false,
  },
  {
    code: "F11",
    value: "F11",
    shiftValue: "",
    index: 11,
    isPress: false,
  },
  {
    code: "F12",
    value: "F12",
    shiftValue: "",
    index: 12,
    isPress: false,
  },
  {
    code: "Backquote",
    value: "`",
    shiftValue: "",
    index: 13,
    isPress: false,
  },
  {
    code: "Digit1",
    value: "1",
    shiftValue: "",
    index: 14,
    isPress: false,
  },
  {
    code: "Digit2",
    value: "2",
    shiftValue: "",
    index: 15,
    isPress: false,
  },
  {
    code: "Digit3",
    value: "3",
    shiftValue: "",
    index: 16,
    isPress: false,
  },
  {
    code: "Digit4",
    value: "4",
    shiftValue: "",
    index: 17,
    isPress: false,
  },
  {
    code: "Digit5",
    value: "5",
    shiftValue: "",
    index: 18,
    isPress: false,
  },
  {
    code: "Digit6",
    value: "6",
    shiftValue: "",
    index: 19,
    isPress: false,
  },
  {
    code: "Digit7",
    value: "7",
    shiftValue: "",
    index: 20,
    isPress: false,
  },
  {
    code: "Digit8",
    value: "8",
    shiftValue: "",
    index: 21,
    isPress: false,
  },
  {
    code: "Digit9",
    value: "9",
    shiftValue: "",
    index: 22,
    isPress: false,
  },
  {
    code: "Digit0",
    value: "0",
    shiftValue: "",
    index: 23,
    isPress: false,
  },
  {
    code: "Minus",
    value: "-",
    shiftValue: "",
    index: 24,
    isPress: false,
  },
  {
    code: "Equal",
    value: "=",
    shiftValue: "",
    index: 25,
    isPress: false,
  },
  {
    code: "Backspace",
    value: "Backspace",
    shiftValue: "",
    index: 26,
    isPress: false,
  },
  {
    code: "Tab",
    value: "Tab",
    shiftValue: "",
    index: 27,
    isPress: false,
  },
  {
    code: "KeyQ",
    value: "Q",
    shiftValue: "",
    index: 28,
    isPress: false,
  },
  {
    code: "KeyW",
    value: "W",
    shiftValue: "",
    index: 29,
    isPress: false,
  },
  {
    code: "KeyE",
    value: "E",
    shiftValue: "",
    index: 30,
    isPress: false,
  },
  {
    code: "KeyR",
    value: "R",
    shiftValue: "",
    index: 31,
    isPress: false,
  },
  {
    code: "KeyT",
    value: "T",
    shiftValue: "",
    index: 32,
    isPress: false,
  },
  {
    code: "KeyY",
    value: "Y",
    shiftValue: "",
    index: 33,
    isPress: false,
  },
  {
    code: "KeyU",
    value: "U",
    shiftValue: "",
    index: 34,
    isPress: false,
  },
  {
    code: "KeyI",
    value: "I",
    shiftValue: "",
    index: 35,
    isPress: false,
  },
  {
    code: "KeyO",
    value: "O",
    shiftValue: "",
    index: 36,
    isPress: false,
  },
  {
    code: "KeyP",
    value: "P",
    shiftValue: "",
    index: 37,
    isPress: false,
  },
  {
    code: "BracketLeft",
    value: "[",
    shiftValue: "",
    index: 38,
    isPress: false,
  },
  {
    code: "BracketRight",
    value: "]",
    shiftValue: "",
    index: 39,
    isPress: false,
  },
  {
    code: "Backslash",
    value: "\\",
    shiftValue: "",
    index: 40,
    isPress: false,
  },
  {
    code: "CapsLock",
    value: "CapsLock",
    shiftValue: "",
    index: 41,
    isPress: false,
  },
  {
    code: "KeyA",
    value: "A",
    shiftValue: "",
    index: 42,
    isPress: false,
  },
  {
    code: "KeyS",
    value: "S",
    shiftValue: "",
    index: 43,
    isPress: false,
  },
  {
    code: "KeyD",
    value: "D",
    shiftValue: "",
    index: 44,
    isPress: false,
  },
  {
    code: "KeyF",
    value: "F",
    shiftValue: "",
    index: 45,
    isPress: false,
  },
  {
    code: "KeyG",
    value: "G",
    shiftValue: "",
    index: 46,
    isPress: false,
  },
  {
    code: "KeyH",
    value: "H",
    shiftValue: "",
    index: 47,
    isPress: false,
  },
  {
    code: "KeyJ",
    value: "J",
    shiftValue: "",
    index: 48,
    isPress: false,
  },
  {
    code: "KeyK",
    value: "K",
    shiftValue: "",
    index: 49,
    isPress: false,
  },
  {
    code: "KeyL",
    value: "L",
    shiftValue: "",
    index: 50,
    isPress: false,
  },
  {
    code: "Semicolon",
    value: ";",
    shiftValue: "",
    index: 51,
    isPress: false,
  },
  {
    code: "Quote",
    value: "'",
    shiftValue: "",
    index: 52,
    isPress: false,
  },
  {
    code: "Enter",
    value: "Enter",
    shiftValue: "",
    index: 53,
    isPress: false,
  },
  {
    code: "ShiftLeft",
    value: "Shift",
    shiftValue: "",
    index: 54,
    isPress: false,
  },
  {
    code: "KeyZ",
    value: "Z",
    shiftValue: "",
    index: 55,
    isPress: false,
  },
  {
    code: "KeyX",
    value: "X",
    shiftValue: "",
    index: 56,
    isPress: false,
  },
  {
    code: "KeyC",
    value: "C",
    shiftValue: "",
    index: 57,
    isPress: false,
  },
  {
    code: "KeyV",
    value: "V",
    shiftValue: "",
    index: 58,
    isPress: false,
  },
  {
    code: "KeyB",
    value: "B",
    shiftValue: "",
    index: 59,
    isPress: false,
  },
  {
    code: "KeyN",
    value: "N",
    shiftValue: "",
    index: 60,
    isPress: false,
  },
  {
    code: "KeyM",
    value: "M",
    shiftValue: "",
    index: 61,
    isPress: false,
  },
  {
    code: "Comma",
    value: ",",
    shiftValue: "<",
    index: 62,
    isPress: false,
  },
  {
    code: "Period",
    value: ".",
    shiftValue: ">",
    index: 63,
    isPress: false,
  },
  {
    code: "Slash",
    value: "/",
    shiftValue: "?",
    index: 64,
    isPress: false,
  },
  {
    code: "ShiftRight",
    value: "Shift",
    shiftValue: "",
    index: 65,
    isPress: false,
  },
  {
    code: "ControlLeft",
    value: "Control",
    shiftValue: "",
    index: 66,
    isPress: false,
  },
  {
    code: "MetaLeft",
    value: "Meta",
    shiftValue: "",
    index: 67,
    isPress: false,
  },
  {
    code: "AltLeft",
    value: "Alt",
    shiftValue: "",
    index: 68,
    isPress: false,
  },
  {
    code: "Space",
    value: " ",
    shiftValue: "",
    index: 69,
    isPress: false,
  },
  {
    code: "AltRight",
    value: "Alt",
    shiftValue: "",
    index: 70,
    isPress: false,
  },
  {
    code: "MetaRight",
    value: "Meta",
    shiftValue: "",
    index: 71,
    isPress: false,
  },
  {
    code: "ContextMenu",
    value: "ContextMenu",
    shiftValue: "",
    index: 72,
    isPress: false,
  },
  {
    code: "ControlRight",
    value: "Control",
    shiftValue: "",
    index: 73,
    isPress: false,
  },
  {
    code: "ScrollLock",
    value: "ScrollLock",
    shiftValue: "",
    index: 74,
    isPress: false,
  },
  {
    code: "Pause",
    value: "Pause",
    shiftValue: "",
    index: 75,
    isPress: false,
  },
  {
    code: "Insert",
    value: "Insert",
    shiftValue: "",
    index: 76,
    isPress: false,
  },
  {
    code: "Home",
    value: "Home",
    shiftValue: "",
    index: 77,
    isPress: false,
  },
  {
    code: "PageUp",
    value: "PageUp",
    shiftValue: "",
    index: 78,
    isPress: false,
  },
  {
    code: "Delete",
    value: "Delete",
    shiftValue: "",
    index: 79,
    isPress: false,
  },
  {
    code: "End",
    value: "End",
    shiftValue: "",
    index: 80,
    isPress: false,
  },
  {
    code: "PageDown",
    value: "PageDown",
    shiftValue: "",
    index: 81,
    isPress: false,
  },
  {
    code: "ArrowUp",
    value: "ArrowUp",
    shiftValue: "",
    index: 82,
    isPress: false,
  },
  {
    code: "ArrowLeft",
    value: "ArrowLeft",
    shiftValue: "",
    index: 83,
    isPress: false,
  },
  {
    code: "ArrowDown",
    value: "ArrowDown",
    shiftValue: "",
    index: 84,
    isPress: false,
  },
  {
    code: "ArrowRight",
    value: "ArrowRight",
    shiftValue: "",
    index: 85,
    isPress: false,
  },
  {
    code: "NumLock",
    value: "NumLock",
    shiftValue: "",
    index: 86,
    isPress: false,
  },
  {
    code: "NumpadDivide",
    value: "/",
    shiftValue: "",
    index: 87,
    isPress: false,
  },
  {
    code: "NumpadMultiply",
    value: "*",
    shiftValue: "",
    index: 88,
    isPress: false,
  },
  {
    code: "NumpadSubtract",
    value: "-",
    shiftValue: "",
    index: 89,
    isPress: false,
  },
  {
    code: "Numpad7",
    value: "7",
    shiftValue: "",
    index: 90,
    isPress: false,
  },
  {
    code: "Numpad8",
    value: "8",
    shiftValue: "",
    index: 91,
    isPress: false,
  },
  {
    code: "Numpad9",
    value: "9",
    shiftValue: "",
    index: 92,
    isPress: false,
  },
  {
    code: "NumpadAdd",
    value: "+",
    shiftValue: "",
    index: 93,
    isPress: false,
  },
  {
    code: "Numpad4",
    value: "ArrowLeft",
    shiftValue: "",
    index: 94,
    isPress: false,
  },
  {
    code: "Numpad5",
    value: "Clear",
    shiftValue: "",
    index: 95,
    isPress: false,
  },
  {
    code: "Numpad6",
    value: "ArrowRight",
    shiftValue: "",
    index: 96,
    isPress: false,
  },
  {
    code: "Numpad1",
    value: "End",
    shiftValue: "",
    index: 97,
    isPress: false,
  },
  {
    code: "Numpad2",
    value: "ArrowDown",
    shiftValue: "",
    index: 98,
    isPress: false,
  },
  {
    code: "Numpad3",
    value: "PageDown",
    shiftValue: "",
    index: 99,
    isPress: false,
  },
  {
    code: "NumpadEnter",
    value: "Enter",
    shiftValue: "",
    index: 100,
    isPress: false,
  },
  {
    code: "Numpad0",
    value: "Insert",
    shiftValue: "",
    index: 101,
    isPress: false,
  },
  {
    code: "NumpadDecimal",
    value: "Delete",
    shiftValue: "",
    index: 102,
    isPress: false,
  },
];

const FUNCTION_KEYS = ALL_KEYS.map((item) => item.code).slice(0, 13);
const PRIMARY_KEYS = {
  LINE1: ALL_KEYS.map((item) => item.code).slice(13, 27),
  LINE2: ALL_KEYS.map((item) => item.code).slice(27, 41),
  LINE3: ALL_KEYS.map((item) => item.code).slice(41, 54),
  LINE4: ALL_KEYS.map((item) => item.code).slice(54, 66),
  LINE5: ALL_KEYS.map((item) => item.code).slice(66, 74),
};

export { ARRANGEMENT, ALL_KEYS, FUNCTION_KEYS, PRIMARY_KEYS };
